# Spring Specific Configuration
spring:
    # Application Contexts to Load.
    applicationContext: ['conf/applicationContext.xml']

    useSpringSecurity: false

    propertyPlaceholderConfigurer:
         ignoreUnresolvablePlaceholders: true
         order: 123
         properties:
             "property.key": "my magic key"
             "property.value": "my magic box"
             "encrytped.passwd" : "<my encrypted password>"
             "some.other.property" : "with its magic value"
             "etc" : "etc value!"


########## Everything else is basic Dropwizard ###################

logging:
  level: DEBUG
  loggers:
        io.dropwizard: INFO
        org: WARN
        com: WARN
        org.tierlon: DEBUG
  #appenders:
  #  - type: console

server:
  type: simple
  applicationContextPath: /
  adminContextPath: /admin
  connector:
    type: http
    port: 8080
